### ISSUE TITLE
Updates for new FBX version

### ISSUE THREAD

**Issue by shyam98** [libgdx/fbx-conv#114]
This tool is super useful but unfortunately there are some limitations in terms of the output file versions, especially for FBX. There could be a lot more utility if there was a way to use the newer fbx sdk and control the export file version. Let me know you are interested or if I can help in any way!

**Comment by mgsx-dev** [comment]
@Tom-Ski i'm currently checking if fbx-conv still compatible with Blender 2.8 and their new default material (Principled BSDF). It looks fine so far but i had an issue with opacity : opaque materials went fully transparent in G3DJ file.
I built fbx-conv locally on linux (thank you for the travis build instructions btw) and it was ok : opacity is 1.0 now.
There was a fix merged #94 a long time ago (nov. 2015) but not included in last release (aug. 2015).
This plus PR #113 make me feel a new release is needed.
Btw, it would be nice to have a versionning (at least tags) in order to know what's in the latest release.

It seems you have trouble configuring build for windows in travis and i guess it blocks a new release. Unfortunately i can't help on Windows stuff.

No pressure, it's just a reminder just in case Blender 2.8 users start to complain and open issues here and there.

**Comment by Tom-Ski** [comment]
Yup, windows is pretty much impossible (on the fbx sdk versions we use). So it has to just be bundled manually which is pretty shit.

I can setup some nodes on jenkins and deploy that way, but it just requires getting round to it.

**Comment by happypandaface** [comment]
yeah, opacity is working after you build it on linux. can confirm
had a time figuring out the makefile though. here's a couple commands I ran to build it roughly complete/in-order:
```
git clone https://github.com/libgdx/fbx-conv.git
wget http://images.autodesk.com/adsk/files/fbx20142_1_fbxsdk_linux.tar.gz
wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz
sudo apt install g++
cd fbx-conv/
FBX_SDK_ROOT=<path>
./generate_makefile
cd fbx-conv/build/gmake/
make -f fbx-conv.make
LD_LIBRARY_PATH=FBX_SDK_ROOT/<path to so>
./bin/Debug/fbx-conv file.fbx output_file.g3dj
```

**Comment by Tom-Ski** [comment]
This is what is used for travis that works https://github.com/libgdx/fbx-conv/blob/master/.travis.yml

**Comment by RUSshy** [comment]
I have updated everything to use latest 2019.0 SDK, so newest version of FBX should work https://github.com/libgdx/fbx-conv/pull/122

It works perfectly fine with my models

If you can test that would be awesome
