### ISSUE TITLE
Vertices values "off" when converting to .g3db format

### ISSUE THREAD

**Issue by CotterPin-Source** [libgdx/fbx-conv#99]
When converting an fbx model from blender to .g3dj, the desired vertex positions are correct, however when converting to .g3db, a good portion of the vertices are very slightly "off".

http://i.imgur.com/EhveAW4.png

The above window shows the proper coordinates created in blender and converted to .g3dj, where the bottom window shows the coordinates generated in the .g3db file.

**Comment by xoppa** [comment]
That's correct, the g3dj file format is slightly less accurate than the g3db format because for g3dj the numbers are rounded to 6 digits for the textual representation, while for g3db the numbers are used as is. That's why you see a difference when comparing the 6 digit rounded g3dj number to your 8 digit rounded numbers textual representation. That's to be expected.
